version: 2

build:
  os: ubuntu-22.04 

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the Python version and install requirements
python:
  install:
    - requirements: requirements.txt
